apiVersion: v1
kind: Pod
metadata:
  name: n8n
spec:
  containers:
  - name: n8n
    image: n8nio/n8n:latest
    ports:
    - containerPort: 5678
      hostPort: 5678
    volumeMounts:
    - mountPath: /home/node/.n8n
      name: n8n-data
    env:
    - name: N8N_BASIC_AUTH_ACTIVE
      value: "true"
    - name: N8N_BASIC_AUTH_USER
      value: "admin"
    - name: N8N_BASIC_AUTH_PASSWORD
      value: "yourpassword"
  volumes:
  - name: n8n-data
    hostPath:
      path: /path/on/host/.n8n
      type: DirectoryOrCreate